// File generated by flutterfire_cli.
// For more information, please see https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:123456789:web:abcdef1234567890abcdef',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    authDomain: 'ai-learning-app-7fe52.firebaseapp.com',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:109914433070:android:8b90d6acbc7db6902a61bf',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:123456789:ios:abcdef1234567890abcdef',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
    iosBundleId: 'com.example.fypV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:123456789:ios:abcdef1234567890abcdef',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
    iosBundleId: 'com.example.fypV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:123456789:windows:abcdef1234567890abcdef',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDyPT9-z_2lmi7snxK2t9eHtLyoCj5AUcE',
    appId: '1:123456789:linux:abcdef1234567890abcdef',
    messagingSenderId: '109914433070',
    projectId: 'ai-learning-app-7fe52',
    storageBucket: 'ai-learning-app-7fe52.firebasestorage.app',
  );
}
